version: '3'
services:
    server:
        build:
            context: ./
            dockerfile: ./server/Dockerfile
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - ./server:/server
        ports:
            - 8000:8000
        depends_on:
            - db
            - redis
        environment:
            DEBUG: 'True'
            DATABASE_URL: 'postgres://postgres:@db:5432/postgres'
            REDIS_URL: 'redis://redis:6379'
            BROKER_URL: 'amqp://user:password@rabbitmq:5672/my_vhost'
        env_file:
            - web-variables.env

    db:
        image: postgres:11.2
        environment:
            POSTGRES_DB: postgres
            POSTGRES_USER: postgres

    redis:
        image: redis
        ports:
            - "6379:6379"
