version: '3'
services:
    nginx:
        build:
            context: ./
            dockerfile: ./nginx/Dockerfile
        depends_on:
            - server
        ports:
            - "80:80"
        volumes:
            - ./server/media:/nginx/media

    server:
        build:
            context: ./
            dockerfile: ./server/Dockerfile
        command: gunicorn config.wsgi -c ./config/gunicorn.py
        expose:
            - 8000
        volumes:
            - ./server/staticfiles:/server/staticfiles
            - ./server/media:/server/media
        depends_on:
            - db
            - redis
        environment:
            DEBUG: 'False'       
            DATABASE_URL: 'postgres://postgres:@db:5432/postgres'
            REDIS_URL: 'redis://redis:6379'
            BROKER_URL: 'amqp://user:password@rabbitmq:5672/my_vhost'
        env_file:
            - ./server/web-variables.env

    db:
        image: postgres:11.2
        environment:
            POSTGRES_DB: postgres
            POSTGRES_USER: postgres

    redis:
        image: redis
        ports:
            - "6379:6379"