# Generated by Django 3.0.8 on 2020-07-26 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='picture',
            field=models.URLField(blank=True),
        ),
    ]
